### ISSUE TITLE
Is this package vulnerable to race conditions?

### ISSUE THREAD

**Issue by Nateowami** [koopero/node-unique-file-name#1]
When it comes to creating unique file names, the straightforward approach is to check whether a particular name exists, and if not, write to that file. However, this is vulnerable to race conditions, because two checks could occur simultaneously. This is an especially important issue as it relates to file uploads, because, if I recall correctly, some devices will always upload files with a particular name, e.g. I think an iPad was once uploading pictures as `file.jpg`. There may have even been an issue where multiple files were being uploaded with the same name at the same time.

My question is, is this package vulnerable to such race conditions? The [fsu package](https://www.npmjs.com/package/fsu) claims to have solved this problem, but it doesn't have all the functionality I was hoping for (In particular, uploading a specially crafted file name would mix up the pattern matching. Your module doesn't have this problem).

And :+1: for creating a module that does what I think all upload modules should do: provide a way to create unique file names that are based on the original name.

EDIT: I didn't specifically mention it, but it's also important to consider what other processes might be doing to the file system. And considering that Node.js is single-threaded, it's often necessary to run a cluster, increasing the risk of race conditions. Even using synchronous functions (generally a bad idea anyway), other processes could modify the file system.

**Comment by koopero** [comment]
Hi @Nateowami !

I think there is a _very_ slight potential for a race condition between calls to `fs.exists` and `fs.ensureFile` (fs-extra). These calls are happening within the same javascript tick, but the implementation of `ensureFile` may have additional delays. This would only be a problem in clustered environments or cases when there are multiple instances of `unf`, since each instance synchronously reserves filenames.

If this still worries you, my suggestion is to use the `%r` token. Adding a random element to the unique file name will drop the potential for collisions to almost zero, with the added bonus of making upload names unguessable.

I will be revisiting this module soon to add some new features and write better docs, so I will look at a more atomic solution to this potential problem.

Thank you for your feedback, it's really appreciated. :)

**Comment by Nateowami** [comment]
Thanks, that's good enough for my current needs.
